# Generated by Django 3.0.6 on 2020-05-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredeint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredeint',
            new_name='Ingredient',
        ),
    ]
